apiVersion: v1
kind: Secret
metadata:
  name: conv-api-secret
type: Opaque
data:
  SEED_USERNAME: ZGVtbw==
  SEED_USER_PASSWORD: ZGVtbw==
  AMQP_EXCHANGE: dGVzdA==
  AMQP_USER: Z3Vlc3Q=
  AMQP_PASSWORD: Z3Vlc3Q=
  AMQP_HOSTNAME: cm1xLWNsdXN0ZXJpcA==