apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.conv_api.name }}-secret"
type: Opaque
data:
  SEED_USERNAME: {{ .Values.cnv.user | b64enc }}
  SEED_USER_PASSWORD: {{ .Values.cnv.password | b64enc }}
  AMQP_EXCHANGE: {{ .Values.cnv.exchange | b64enc }}
  AMQP_USER: {{ .Values.cnv.user | b64enc }}
  AMQP_PASSWORD: {{ .Values.cnv.password | b64enc }}
  AMQP_HOSTNAME: {{ .Values.cnv.hostname | b64enc }}  