apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rmq.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: {{ .Values.rmq.components }}
  template:
    metadata:      
      labels:
        components: {{ .Values.rmq.components }}
    spec:
      containers:
      - name: {{ .Values.rmq.name }}
        image: "{{ .Values.rmq.image }}:{{ .Values.rmq.version }}"
        ports:
        - containerPort: {{ .Values.rmq.port }}
        resources:
          limits:
            memory: {{ .Values.rmq.limits | toYaml | nindent 14 }}
        env:
          {{- range .Values.rmq.envs }}
          {{- $data := dict "name" $.Values.rmq.name "env" . }}
          {{- include "env.template" $data | indent 12 }}
          {{- end }}            

        volumeMounts:
          - name: "{{ .Values.rmq.name }}-data"
            mountPath: /var/lib/rabbitmq
            subPath: mnesia
      volumes:
        - name: "{{ .Values.rmq.name }}-data"
          persistentVolumeClaim:
            claimName: "{{ .Values.rmq.name }}-pvc"        
