apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.rmq.name }}-secret"
type: Opaque
data:  
  SEED_USERNAME: {{ .Values.rabbitmq.user | b64enc }}
  SEED_USER_PASSWORD: {{ .Values.rabbitmq.password | b64enc }}