apiVersion: v1
kind: Secret
metadata:
  name: converter-secret
type: Opaque
data:
  AMQP_EXCHANGE: dGVzdA==
  AMQP_USER: Z3Vlc3Q=
  AMQP_PASSWORD: Z3Vlc3Q=
  AMQP_HOSTNAME: cm1xLWNsdXN0ZXJpcA==
  AMQP_QUEUE: Y29udmVydGVy